### ISSUE TITLE
Use single or multiple leaf pairs?

### ISSUE THREAD

**Issue by koosvanamerongen** [MatthewPeterKelly/FluenceMapping#15]
We should decide whether to use one or multiple leaf pairs.
More leaf pairs is more realistic and better tests the dose rate space search, but is harder to illustrate and might require more space to visualize, deviating attention from the core.

**Comment by MatthewPeterKelly** [comment]
I could see an argument for both ways. One option would be to focus on the core concepts in the body of the paper, but include a single figure that illustrates how the method works for multiple leaves. 

David - would you be able to send me an example of what the fluence targets might look like for a set of multiple leaf pairs?

**Comment by koosvanamerongen** [comment]
I believe we decided the following: We'll use all fluence rows for the CORT dataset's prostate case. We explain the inner single leaf trajectory optimization loop using one fluence row and show the trajectory of one central leaf row in the results section, but other than that use multi-leaf language.
