### ISSUE TITLE
Which sample data to use?

### ISSUE THREAD

**Issue by koosvanamerongen** [MatthewPeterKelly/FluenceMapping#24]
I believe we decided to use the 2nd fluence map from the prostate case in the CORT dataset in both its original and transposed form. Agreed?
Also, we only illustrate the methods on what we call "tough rows" as the leaf trajectories of the other rows can be optimized indivually for a given dose rate pattern and typically result in near-perfect matching.

**Comment by MatthewPeterKelly** [comment]
Since we are using a fixed dose rate, we can completely decouple the rows of the data set. I suggest that we select two rows (or columns) from the CORT data set, one which illustrates a unimodal data set, and one which illustrates a bimodal data set. I'll pick two when I generate the smoothing data, and then report which ones here.

**Comment by koosvanamerongen** [comment]
We may use one or two (preferably central) rows to illustrate our main idea, but I'd suggest to use all ("though") rows in at least one part of the results section, despite the row-wise decoupling of the leaf trajectory optimization problem. This allows us to show a (delivery time vs delivery quality + delivered maps) figure like the one we've been using so far and may - depending on #23 - appeal more to the reader.

**Comment by MatthewPeterKelly** [comment]
Is there a good reason to use data from a real case, as opposed to just using simulated data that is similar? For example, I am running the parameter tests (at least for the first pass) using two simulated fluence profiles: one has a single peak and the other has two peaks. Is there some key feature that we get from using data from a real case? I looked through the CORT case and most of the rows that I was finding were unimodal, and pretty noisy.

@koosvanamerongen - Take a look at the function below that gives sample data for the single-row experiments. Would you be able to let me know if this looks good, or if not, look through the CORT data set and pick a few rows that are good examples and then encode them as additional cases in the function?

    function data = getSimData(name, nData)

    if nargin < 1
        name = 'bimodal';
    end
    if nargin < 2
        nData = 20;
    end

    xGrid = linspace(0, 10, 6);

    switch name
        case 'unimodal'
            fGrid = [0, 5, 12, 32, 15, 0];    
        case 'bimodal'
            fGrid = [0, 20, 12, 30, 35, 0];        
        otherwise
            error('Invalid data name!')
    end

    data.x = linspace(xGrid(1), xGrid(end), nData);
    data.f = spline(xGrid, fGrid, data.x);
    data.maxLeafSpeed = 3;
    data.maxDoseRate = 10;

    end

**Comment by koosvanamerongen** [comment]
Using real data might appeal more to the reader, but in terms of algorithm performance I don't expect too much difference relative to using a simulated case. For the prostate case from the CORT dataset we are using, the fluence rows are mostly unimodal from a horizontal perspective, but from a vertical perspective they are more bimodal-like. For other treatment sites more complicated fluence rows/maps may arise. 
Okay, I will have a look at this tommorow.

**Comment by MatthewPeterKelly** [comment]
Great - thanks!

The code runs fast, so all we would need to do is update the above function and re-run the function to get an updated figure.

**Comment by koosvanamerongen** [comment]
The fluence profiles you chose are okay for small delivery times (they are rather narrow, so don't need that much time to deliver). However, I propose to only use data from the CORT dataset. Reversing your question: Is there a good reason to use simulated data opposed to using data from a real case?

These rows from the CORT prostate case should work, both having 13 bixels of 1cm wide:
- unimodal: [0 0 0 5.55 9.55 10.16 12.44 18.07 24.52 22.34 18.68 16.74 13.62] (row 11, second map)
- bimodal: [0 0 1.98 7.08 4.84 4.85 0.26 0 5.20 15.88 23.02 18.90 17.99] (row 12, second map)
I am not sure about the relation between data.x, xGrid and nData in your function, that's why I just write the profiles down like this. Does that work?

**Comment by MatthewPeterKelly** [comment]
That looks great - I'll use the data from those sets. 

There is not really a good reason to use simulated data, apart from it is simple and easy.

I'll plan to update the script and plots sometime during the week if I can.

**Comment by MatthewPeterKelly** [comment]
The results are now generated using the Cort data set. I also updated the figures in ShareLaTeX
