### ISSUE TITLE
Leaf trajectories should not cross

### ISSUE THREAD

**Issue by MatthewPeterKelly** [MatthewPeterKelly/FluenceMapping#3]
The code as implemented now has leaf trajectories that are allowed to cross each other. An additional constraint is needed in the optimization to prevent this.

**Comment by koosvanamerongen** [comment]
Actually, the leaf collision constraint is never binding. That is, any combination of left and right leaf trajectories that violate this constraint (at one or several moments in time) but satisfy all other constraints, one can rewrite those trajectories into ones that satisfy all of the constraints, without changing the objective. [This small fact is part of my thesis]. As long as you make sure that, naturally, int_a^b with b<a is 0. So, if at some moment in time the leaves collide, just act like they touch and depose no fluence in between. The same holds when leaf trajectories are defined in terms of passing times.
So, we could omit this constraint from the optimization and write a procedure that checks if the leaf trajectories cross and if so, smooth those out, all at the very end of our procedure (outside of the outer dose rate seach loop).

**Comment by koosvanamerongen** [comment]
@MatthewPeterKelly, did you end up programming this constraint or left it out and use a post-processing step to make the resulting leaf trajectories that possibly violate the leaf collision constraint feasible?

**Comment by MatthewPeterKelly** [comment]
The new version of the code handles this as an inequality constraint on the decision variables, so any feasible solution will have non-colliding leaf trajectories.
