### ISSUE TITLE
Which configuration of smoothing parameters do we want to use in the sensitivity analysis part?

### ISSUE THREAD

**Issue by koosvanamerongen** [MatthewPeterKelly/FluenceMapping#31]

**Comment by MatthewPeterKelly** [comment]
I'm not sure to which sensitivity analysis this is referring. @koosvanamerongen - can you add more detail?

**Comment by koosvanamerongen** [comment]
I was referring to the sensitivity of the objective value(s) of the optimal solution in the various smoothing parameters, but by studying various smoothing parameter configurations/schemes, this is already covered.
