### ISSUE TITLE
How do we quantify/visualize the effect of the various smoothing tools?

### ISSUE THREAD

**Issue by koosvanamerongen** [MatthewPeterKelly/FluenceMapping#32]

**Comment by MatthewPeterKelly** [comment]
The primary side-effect of the smoothing is that it makes the model slightly inaccurate. Thus, one way to quantify smoothing is to start with a given set of dose-rate and leaf trajectories and then compute the delivered fluence using a range of different smoothing values. The error can then be plotted against smoothing parameter.

@koosvanamerongen @davidcraft -- Let me know if this sounds good and I can generate a plot to add to the paper.

**Comment by koosvanamerongen** [comment]
This sounds like a good way to illustrate how the smoothing parameters work. Shall we also make a subfigure of the step function s(x,alpha) for a few (0, small, large) smoothing parameter values alpha and a few, say 2, positions x, to support equations (4) and (5)? I think it should be clear from the formulas, but do we think that also holds for our audience? I guess that also depends on where we would like to submit this paper, see issue #23 .

**Comment by MatthewPeterKelly** [comment]
I can make a small figure for the leaf smoothing

**Comment by MatthewPeterKelly** [comment]
I added the figure for leaf smoothing to the paper.
